/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LoadingRouteImport } from './routes/loading'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicSpotifyRouteImport } from './routes/api/public/spotify'
import { Route as ApiPublicProxyRouteImport } from './routes/api/public/proxy'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LoadingRoute = LoadingRouteImport.update({
  id: '/loading',
  path: '/loading',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSpotifyRoute = ApiPublicSpotifyRouteImport.update({
  id: '/api/public/spotify',
  path: '/api/public/spotify',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicProxyRoute = ApiPublicProxyRouteImport.update({
  id: '/api/public/proxy',
  path: '/api/public/proxy',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/loading': typeof LoadingRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/api/public/proxy': typeof ApiPublicProxyRoute
  '/api/public/spotify': typeof ApiPublicSpotifyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/loading': typeof LoadingRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/api/public/proxy': typeof ApiPublicProxyRoute
  '/api/public/spotify': typeof ApiPublicSpotifyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/loading': typeof LoadingRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/api/public/proxy': typeof ApiPublicProxyRoute
  '/api/public/spotify': typeof ApiPublicSpotifyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/loading'
    | '/login'
    | '/reset-password'
    | '/api/public/proxy'
    | '/api/public/spotify'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/loading'
    | '/login'
    | '/reset-password'
    | '/api/public/proxy'
    | '/api/public/spotify'
  id:
    | '__root__'
    | '/'
    | '/loading'
    | '/login'
    | '/reset-password'
    | '/api/public/proxy'
    | '/api/public/spotify'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoadingRoute: typeof LoadingRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ApiPublicProxyRoute: typeof ApiPublicProxyRoute
  ApiPublicSpotifyRoute: typeof ApiPublicSpotifyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loading': {
      id: '/loading'
      path: '/loading'
      fullPath: '/loading'
      preLoaderRoute: typeof LoadingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/spotify': {
      id: '/api/public/spotify'
      path: '/api/public/spotify'
      fullPath: '/api/public/spotify'
      preLoaderRoute: typeof ApiPublicSpotifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/proxy': {
      id: '/api/public/proxy'
      path: '/api/public/proxy'
      fullPath: '/api/public/proxy'
      preLoaderRoute: typeof ApiPublicProxyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoadingRoute: LoadingRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ApiPublicProxyRoute: ApiPublicProxyRoute,
  ApiPublicSpotifyRoute: ApiPublicSpotifyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
